# Generated by Django 3.1.1 on 2020-09-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='BWUser',
        ),
    ]
