# Generated by Django 3.1.1 on 2020-09-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer_id',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='high_price',
            field=models.IntegerField(verbose_name=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(verbose_name=20),
        ),
    ]
