# Generated by Django 3.1.1 on 2020-09-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0004_auto_20200930_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='high_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
