# Generated by Django 3.1.1 on 2020-09-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0005_auto_20200930_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_day_left',
            field=models.IntegerField(null=True),
        ),
    ]
