# Generated by Django 3.1.1 on 2020-09-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0006_product_auction_day_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_name',
        ),
    ]
