# Generated by Django 3.1.1 on 2020-09-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0007_auto_20200930_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product_data',
        ),
    ]
