# Generated by Django 3.1.1 on 2020-09-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0008_auto_20200930_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchist_data',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
