# Generated by Django 3.1.1 on 2020-09-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0010_auto_20200930_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchist_data',
            new_name='watchlist_data',
        ),
    ]
