# Generated by Django 3.1.1 on 2020-10-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0012_auto_20200930_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BidderWeb.bwuser'),
        ),
    ]
