# Generated by Django 3.1.1 on 2020-10-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0013_auto_20201001_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('my_price', models.IntegerField(blank=True, null=True)),
                ('cart_user_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BidderWeb.product_data')),
            ],
        ),
    ]
