# Generated by Django 3.1.1 on 2020-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidderWeb', '0014_cart_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedular_flag',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('m', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
